# -*- coding: utf-8 -*-
"""helloworld_github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uAKi9XuUnY4fEE9ni-lkQ9Gz66TSFR-_
"""

print("Hello World!")